# Generated by Django 4.2.4 on 2023-08-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_tag_snippet_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='copy_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
